// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import support from "../../agent_sdk/support/entidad";
// END EXTRA CODE

/**
 * Update editable properties of user profile record and persist in repository
 *  @param props new user data (only fields that have changed)
 *  @returns updated User Profile data
 * @param {string} agent_key
 * @param {string} profileData_displayName
 * @param {string} profileData_displayPicture
 * @param {string} profileData_description
 * @returns {Promise.<string>}
 */
export async function jsa_aries_agent_modules_userProfile_updateUserProfileData(agent_key, profileData_displayName, profileData_displayPicture, profileData_description) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		return(Promise.resolve(JSON.stringify(await agent.modules.userProfile.updateUserProfileData({
				displayName:profileData_displayName,
				displayPicture:profileData_displayPicture,
				description:profileData_description
		}),0,2)));
	}catch(e){
		return Promise.reject(e.toString());
	}

	// END USER CODE
}
