// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import{cache}from"../support/entidad";
// END EXTRA CODE

/**
 * registerOnDiscoveredListener(cb: ({ identifier, name }: { identifier: string; name?: string; }) => void): EmitterSubscription
 * @param {Nanoflow} callback
 * @param {string} identifier_parameter_name - optional
 * @param {string} name_parameter_name - optional
 * @param {MxObject} user_data - optional
 * @param {string} user_data_parameter_name - optional
 * @returns {Promise.<void>}
 */
export async function jsa_animo_ble_central_registerOnDiscoveredListener(callback, identifier_parameter_name, name_parameter_name, user_data, user_data_parameter_name) {
	// BEGIN USER CODE
	try{
		if(callback==null)return(Promise.reject("callback null"));
		if(identifier_parameter_name==null)identifier_parameter_name='identifier';
		if(name_parameter_name==null)name_parameter_name='name';
		if(user_data_parameter_name==null)user_data_parameter_name='Central';
		let central=cache.get("central");
		if(central==null)return(Promise.reject("Central not found in cache"));
		//registerOnDiscoveredListener(cb: ({ identifier, name }: { identifier: string; name?: string; }) => void): EmitterSubscription
		central.registerOnDiscoveredListener(({identifier,name})=>{
			try{
				let args={};
				if(identifier_parameter_name!=null)args[identifier_parameter_name]=typeof(identifier)=="undefined"?null:identifier;
				if(name_parameter_name!=null)args[name_parameter_name]=typeof(name)=="undefined"?null:name;
				if(user_data_parameter_name!=null)args[user_data_parameter_name]=user_data;
				callback(args);
			}catch(e){
				console.error("jsa_animo_ble_central_registerOnDiscoveredListener:registerOnDiscoveredListener:callback:"+e.toString());
			}
		});
		return(Promise.resolve());
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
