// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import "../../agent_sdk/shim.js";
import {
  PermissionsAndroid
} from 'react-native'
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function jsa_android_request_ble_permissions() {
	// BEGIN USER CODE
	try{
		await PermissionsAndroid.requestMultiple([
			'android.permission.ACCESS_FINE_LOCATION',
			'android.permission.BLUETOOTH_CONNECT',
			'android.permission.BLUETOOTH_SCAN',
			'android.permission.BLUETOOTH_ADVERTISE',
			'android.permission.ACCESS_COARSE_LOCATION'
		]);
		return(Promise.resolve());
  	}catch(e){
		return(Promise.reject(e.toString()));
	}
	// END USER CODE
}
