// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import "../../agent_sdk/shim.js";
import{
	Peripheral
}from"../../agent_sdk/node_modules/@animo-id/react-native-ble-didcomm";
import{cache}from"../support/entidad";
// END EXTRA CODE

/**
 * create peripheral
 * @returns {Promise.<void>}
 */
export async function jsa_animo_ble_peripheral_create() {
	// BEGIN USER CODE
	try{
		const peripheral=new Peripheral();
		cache.put(peripheral,"peripheral");
		return Promise.resolve();
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
