// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package guidgenerator.actions;

import java.util.UUID;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * A simple function for creating Guids. Useful for when you want exposed unique ids for objects used with REST APIs.
 * 
 * Uses java.util.uuid
 * 
 * See https://www.geeksforgeeks.org/java-util-uuid-class-java/ for more information.
 */
public class CreateGuid extends UserAction<java.lang.String>
{
	public CreateGuid(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
				 UUID uuid = UUID.randomUUID();
			     return uuid.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateGuid";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
