// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import support from"../../../javascriptsource/agent_sdk/support/entidad";
// END EXTRA CODE

/**
 * public async request(options: MediaSharingRequestOptions)
 * 
 * Receiver role: request media
 * @param {string} agent_key
 * @param {string} options - json
 * @param {string} items - json array
 * @returns {Promise.<string>}
 */
export async function jsa_agent_modules_mediasharing_request(agent_key, options, items) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");
		if(options==null)return Promise.reject("Invalid options parameter");
		try{
			options=JSON.parse(options);
		}catch(e){
			return(Promise.reject(e.toString()));
		}
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		let record=await agent.modules.media.request(options);
		return Promise.resolve(JSON.stringify(await agent.modules.media.request(options)));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
