// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<string>}
 */
export async function jsa_nonce() {
	// BEGIN USER CODE
	try{
		let arr = new Uint8Array(32);
		crypto.getRandomValues(arr);
		let nonce=btoa(String.fromCharCode.apply(null,arr))
		return(Promise.resolve(nonce))
	}catch(e){
		return(Promise.reject(e.toString()));
	}
	// END USER CODE
}
