// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package testharness.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import java.security.KeyPairGenerator;
import java.security.spec.ECGenParameterSpec;
import java.security.SecureRandom;
import java.security.KeyPair;
import java.security.PrivateKey;
import org.bouncycastle.asn1.DEROctetString;
import org.bouncycastle.asn1.DERSequence;

/**
 * https://stackoverflow.com/questions/63568619/elliptic-curve-private-key-length-in-java
 * https://stackoverflow.com/questions/42639620/generate-ecpublickey-from-ecprivatekey
 */
public class ja_pk_secp256r1 extends CustomJavaAction<java.lang.String>
{
	public ja_pk_secp256r1(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String ret=null;
		try{
			//https://stackoverflow.com/questions/63568619/elliptic-curve-private-key-length-in-java
			//https://stackoverflow.com/questions/42639620/generate-ecpublickey-from-ecprivatekey
			KeyPairGenerator kpg=KeyPairGenerator.getInstance("EC");//,"provider");
			kpg.initialize(new ECGenParameterSpec("secp256r1"),new SecureRandom());
			KeyPair ecKeyPair=kpg.generateKeyPair();
			PrivateKey privateKey=ecKeyPair.getPrivate();
			byte[]pkcs8=privateKey.getEncoded();
			DEROctetString wrapped=(DEROctetString)DERSequence.getInstance(pkcs8).getObjectAt(2);
			//com.mendix.core.Core.getLogger(this.toString()).info(wrapped.getOctets().length);
			DEROctetString raw=(DEROctetString) DERSequence.getInstance(wrapped.getOctets()).getObjectAt(1);
			//com.mendix.core.Core.getLogger(this.toString()).info(raw.getOctets().length);
			//com.mendix.core.Core.getLogger(this.toString()).info(raw);
			ret=raw.toString();
		}catch(Exception e){
			com.mendix.core.Core.getLogger(this.toString()).error(e.toString());
			throw(e);
		}
		return ret;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ja_pk_secp256r1";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
