// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import "../shim.js";
import support from "../support/entidad";
import {fetchSchema} from "@credo-ts/anoncreds"
// END EXTRA CODE

/**
 * fetchSchema(agentContext: AgentContext, schemaId: string): Promise<{ schema: AnonCredsSchema; schemaId: string; indyNamespace: string; }>
 * @param {string} agent_key
 * @param {string} schemaId
 * @returns {Promise.<string>}
 */
export async function jsa_aries_agent_modules_anoncreds_fetchSchema(agent_key, schemaId) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");
		if(schemaId==null)throw("Invalid schemaId");
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		return(Promise.resolve(JSON.stringify(await fetchSchema(agent.context,schemaId))));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
