// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import "../shim.js";
// END EXTRA CODE

/**
 * @param {string} text
 * @param {Big} length
 * @param {string} pad
 * @returns {Promise.<string>}
 */
export async function jsa_string_pad_right(text, length, pad) {
	// BEGIN USER CODE
	try{
		if(text==null)throw("Invalid text argument");
		if(length==null||length<0)throw("Invalid length argument");
		if(pad==null||pad.length==0)throw("Invalid pad argument");
		let ret=text;
		for(let i=0;i<length-text.length;i++){
			ret=ret+pad;
		}
		return Promise.resolve(ret);
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
