// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import "../shim.js";
import { isValidPrivateKey } from '@credo-ts/core';
import { KeyType } from '@credo-ts/core';
import { Buffer } from '@credo-ts/core';

// END EXTRA CODE

/**
 * isValidSeed(seed: Buffer, keyType: KeyType): boolean
 * 
 * https://github.com/openwallet-foundation/credo-ts/blob/59c7e15259af0d258cb07996d76cc0b2742c88ad/packages/core/src/crypto/keyUtils.ts
 * @param {string} privateKey - json array
 * @param {undefined|"Bls12381g1"|"Bls12381g1g2"|"Bls12381g2"|"Ed25519"|"X25519"|"K256"|"P256"|"P384"|"P521"} keyType
 * @returns {Promise.<boolean>}
 */
export async function jsa_aries_core_utils_crypto_keyUtils_isValidPrivateKey(privateKey, keyType) {
	// BEGIN USER CODE
	try{
		if(privateKey==null)return(Promise.reject("privateKey null"));
		try{
			privateKey=JSON.parseprivateKey)
		}catch(e){
			return(Promise.reject("privateKey is not a json array: "+e.toString()));
		}
		privateKey=Buffer.from(privateKey);
		if(!Buffer.isBuffer(privateKey))return(Promise.reject("privateKey is not a buffer"));
		if(keyType==null)return(Promise.reject("keyType null"));
		switch(keyType){
			case"Bls12381g1":
				keyType=KeyType.Bls12381g1;
				break;
			case"Bls12381g1g2":
				keyType=KeyType.Bls12381g1g2;
				break;
			case"Bls12381g2":
				keyType=KeyType.Bls12381g2;
				break;
			case"Ed25519":
				keyType=KeyType.Ed25519;
				break;
			case"K256":
				keyType=KeyType.K256;
				break;
			case"P256":
				keyType=KeyType.P256;
				break;
			case"P384":
				keyType=KeyType.P384;
				break;
			case"P521":
				keyType=KeyType.P521;
				break;
			case"X25519":
				keyType=KeyType.X25519;
				break;
  			default:
				return(Promise.reject("Unimplemented key type"));
		}
		return(Promise.resolve(isValidPrivateKey(privateKey,keyType)));
	}catch(e){
		return(Promise.reject(e.toString()));
	}
	// END USER CODE
}
