// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import "../shim.js";
//import{MediatorPickupStrategy}from'@aries-framework/core'
import support from"../support/entidad";
// END EXTRA CODE

/**
 * pickupMessages(mediatorConnection: AriesCore.ConnectionRecord, pickupStrategy?: AriesCore.MediatorPickupStrategy): Promise<void>
 * @param {string} agent_key
 * @param {string} pickupMessagesOptions - json
 * @returns {Promise.<string>}
 */
export async function jsa_aries_agent_messagereceiver_pickupMessages(agent_key, pickupMessagesOptions) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");						//mandatory
		if(pickupMessagesOptions=="")return Promise.reject("Invalid pickupMessagesOptions parameter");		//mandatory
	
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		let messagesRecords=null;
		
		await agent.messagePickup.pickupMessages(pickupMessagesOptions);
		messagesRecords = await basicMessagePromise;
		return Promise.resolve(JSON.stringify(messagesRecords));
		
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
