// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import { Key as AskarKey, KeyAlgs } from '@hyperledger/aries-askar-react-native';
import{Store} from '@hyperledger/aries-askar-shared'
import { WalletApi } from '@credo-ts/core';

// END EXTRA CODE

/**
 * @returns {Promise.<string>}
 */
export async function jsa_tmp() {
	// BEGIN USER CODE
	try{
		console.info(typeof(WalletApi));
		let rk1=Store.generateRawKey();//
		Store.generateRawKey()
		console.info(rk1);
		//let rk2= AskarKey.generate();//crashes
		//console.info(rk2);
		/*
		const askarKey = AskarKey.fromSecretBytes({
			algorithm: KeyAlgs.EcSecp256r1,
			secretKey: new Uint8Array(TypedArrayEncoder.fromHex("12341234ABCD")),
		});
		*/
		return(Promise.resolve("test123"));
	}catch(e){
		return(Promise.reject(e.toString()));
	}
	// END USER CODE
}
