// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import support from"../support/entidad";
//import{CredentialEventTypes,CredentialState}from"@aries-framework/core";
import{filter,firstValueFrom,merge,first,timeout}from"rxjs";
// END EXTRA CODE

/**
 *   const credentialOffer = agent.events
 *     .observable<CredentialStateChangedEvent>(CredentialEventTypes.CredentialStateChanged)
 *     .pipe(
 *       filter((event) => event.payload.credentialRecord.state === CredentialState.OfferReceived),
 *       filter((event) => event.payload.credentialRecord.connectionId === connectionId)
 *     )
 * @param {string} agent_key
 * @param {string} connectionId - string
 * @returns {Promise.<string>}
 */
export async function jsa_aries_util_event_wait_for_credentialOffer(agent_key, connectionId) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		const credentialOffer=agent.events
		.observable/*<CredentialStateChangedEvent>*/(CredentialEventTypes.CredentialStateChanged)
		.pipe(
			filter((event) => event.payload.credentialRecord.state === CredentialState.OfferReceived),
			filter((event) => event.payload.credentialRecord.connectionId === connectionId)
		);
		return Promise.resolve(JSON.stringify(credentialOffer,0,2));
	}catch(e){
		return Promise.reject(e.toString());
	}
	throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
