// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import "../shim.js";
//import*as p from'@aries-framework/core/package.json';
import*as p from'@credo-ts/core/package.json';
// END EXTRA CODE

/**
 * Constructs a new Agent object based on configuration options given
 * Caches constructed object in the running javascript context
 * Returns a string value, the walletConfig id, that can be used to perform further operations on the constructed Agent object
 * @returns {Promise.<string>}
 */
export async function jsa_aries_core_version() {
	// BEGIN USER CODE
	try{
		return Promise.resolve(p.version);
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
