// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import "../shim.js";
import support from "../support/entidad";
import { AgentConfig } from '@credo-ts/core';
import { AgentDependencies } from '@credo-ts/core';

// END EXTRA CODE

/**
 * @param {string} agent_key
 * @param {string} agent_label - Override the agent label initialized from default config
 * @returns {Promise.<void>}
 */
export async function jsa_credo_agent_config_set_label(agent_key, agent_label) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");	//mandatory
		if(agent_label==null)return Promise.reject("Invalid agent_label parameter");	//mandatory
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		
		agent.config.label = agent_label;
		
		return Promise.resolve();

	}catch(e){
		return Promise.reject(e.toString());
	}
	
	// END USER CODE
}
