// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * https://apidocs.rnd.mendix.com/9/client/mendix_lib_MxObject.html
 * 
 * get(attr) → {string|number|external:Big|boolean}
 * 
 * Returns the value of an attribute.
 * Parameters:
 * Name  Type  Description
 * attr  string  
 * 
 * attribute whose value to return
 * 
 * Returns:
 * 
 * value of the specified attribute. The return type depends on the type of the attribute as follows:
 * Attribute type  Javascript type  Javascript value
 * Integer, Long, Decimal  external:Big  instance containing the number
 * Autonumber  string  string representation of the number
 * DateTime  number  timestamp of the date
 * Enum  string  value of the enumeration
 * String  string  
 * Boolean  boolean  
 * Reference  string  referenced object GUID as a string
 * ReferenceSet  Array<string>  referenced object GUIDs as strings
 * 
 * Empty values are always returned as the empty string ("").
 * 
 * Type
 *     string | number | external:Big | boolean 
 * @param {MxObject} input
 * @param {Nanoflow} attribute
 * @returns {Promise.<string>}
 */
export async function jsa_mxobj_get(input, attribute) {
	// BEGIN USER CODE
	try{
		if(input==null)return Promise.reject("Invalid argument input");
		//todo:cast, e.g. numericValue instanceof Big // true
		return Promise.resolve(input.get(attribute));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
