// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * https://apidocs.rnd.mendix.com/9/client/mendix_lib_MxObject.html
 * 
 * addReference(attr, guid) → {boolean}
 * 
 * If attr is a reference attribute, sets it to the given object. If attr is a reference set attribute, adds the given object to it.
 * Parameters:
 * Name  Type  Description
 * attr  string  
 * 
 * The reference attribute. Can refer to either a reference or reference set attribute.
 * guid  GUID  
 * 
 * GUID of the object to add to the reference
 * 
 * Returns:
 * 
 * true if successful, false otherwise
 * 
 * Type
 *     boolean 
 * 
 * Example
 * 
 * mxobj.addReference("MyFirstModule.Ent_RefEnt", "12345");
 * @param {MxObject} input
 * @param {string} attribute
 * @param {string} guid_
 * @returns {Promise.<boolean>}
 */
export async function jsa_mxobj_addReference(input, attribute, guid_) {
	// BEGIN USER CODE
	try{
		if(input==null)return Promise.reject("Invalid argument input");
		//todo:handle return type serialization
		return Promise.resolve(input.addReference(attribute,guid));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
