// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Serializes input typeparameter Mendix object  to JSON string
 * @param {MxObject} input
 * @returns {Promise.<string>}
 */
export async function jsa_mxobj2json(input) {
	// BEGIN USER CODE
	try{
		let json={};
		input.getAttributes().forEach((attr)=>{
			if(input.isReadonlyAttr(attr)){
				json[attr]=input.get(attr);
			}
			else if(input.isBoolean(attr)){
				json[attr]=input.get(attr);
			}
			else if(input.isDate(attr)){
				json[attr]=input.get(attr);
			}
			else if(input.isEnum(attr)){
				json[attr]=input.get(attr);
			}
			else if(input.isLocalizedDate(attr)){
				json[attr]=input.get(attr);
			}
			else if(input.isNumeric(attr)){
				json[attr]=Number(input.get(attr));
			}
			else if(input.isObjectReference(attr)){
				json[attr]=input.get(attr);
			}
			else if(input.isObjectReferenceSet(attr)){
				json[attr]=input.get(attr);
			}
			else if(input.isPassword(attr)){
				json[attr]=input.get(attr);
			}
			else if(input.isReference(attr)){
				json[attr]=input.get(attr);
			}
			else{//string
				json[attr]=input.get(attr);
			}
		});
		return Promise.resolve(JSON.stringify(json));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
