// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} sharedPreferencesName
 * @param {string} key
 * @returns {Promise.<string>}
 */
export async function jsa_web_getItem(sharedPreferencesName, key) {
	// BEGIN USER CODE
	return new Promise(function(resolve,reject){
		try{
			let data=localStorage.getItem(sharedPreferencesName);
			data=JSON.parse((data==null||data=='')?'{}':data);
			resolve(data[key]);
		}catch(e){
			reject(e.toString());
		}
	});
	// END USER CODE
}
