// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * https://apidocs.rnd.mendix.com/9/client/mendix_lib_MxObject.html
 * 
 * removeReferences(attr, guids) → {boolean}
 * 
 * Removes references from a reference attribute.
 * Parameters:
 * Name  Type  Description
 * attr  string  
 * 
 * refererence attribute to remove references from
 * guids  Array.<GUID>  
 * 
 * GUIDs of the objects to remove from the reference
 * 
 * Returns:
 * 
 * false if an exception occured while removing the reference, true otherwise
 * 
 * Type
 *     boolean 
 * 
 * Example
 * 
 * mxobj.removeReferences("MyFirstMdule.Ent_RefEnt", ["12345", "12346"]);
 * @param {MxObject} input
 * @param {string} attribute
 * @param {string} guids
 * @returns {Promise.<boolean>}
 */
export async function jsa_mxobj_removeReferences(input, attribute, guids) {
	// BEGIN USER CODE
	try{
		if(input==null)return Promise.reject("Invalid argument input");
		//todo:handle return type serialization
		return Promise.resolve(input.removeReferences(attribute,guids));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
