// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
import DeviceInfo from 'react-native-device-info';
// END EXTRA CODE

/**
 * @returns {Promise.<string>}
 */
export async function jsa_getsystemname() {
	// BEGIN USER CODE
	try{
		//android
		//ios
		//emulator
		//web
		return Promise.resolve(DeviceInfo.getSystemName());        
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
