// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * https://apidocs.rnd.mendix.com/9/client/mendix_lib_MxObject.html
 * 
 * getReference(reference) → {string}
 * 
 * Retrieves the GUID of the object referenced by a reference attribute. When trying to retrieve a non-reference or reference set attribute this way, an exception is thrown.
 * Parameters:
 * Name  Type  Description
 * reference  string  
 * 
 * attribute whose referenced object to return
 * 
 * Returns:
 * 
 * GUID of the MxObject referenced by the given reference attribute
 * 
 * Type
 *     string 
 * 
 * Example
 * 
 * // Get GUID of object over association MyFirstModule.Ref.
 * refs = mxobj.getReference("MyFirstModule.Ref"); // "12345"
 * @param {MxObject} input
 * @param {string} reference
 * @returns {Promise.<string>}
 */
export async function jsa_mxobj_getReference(input, reference) {
	// BEGIN USER CODE
	try{
		if(input==null)return Promise.reject("Invalid argument input");
		//todo:handle return type serialization
		return Promise.resolve(input.getReference(attribute));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
