// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import "mx-global";
import ImagePicker from "react-native-image-crop-picker";
import NativeFileDocumentsUtils from "../nativefiledocumentsutils";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Cleanup temp files created by the cropper library.
 * @param {boolean} writeToLog
 * @returns {Promise.<void>}
 */
export async function cropImageCleanupTempFiles(writeToLog) {
	// BEGIN USER CODE
	try {
		await ImagePicker.clean();
		if (writeToLog) {
			await NativeFileDocumentsUtils.writeToLog({
				actionName: "cropImageCleanupTempFiles",
				logType: "Info",
				logMessage: "Cleanup complete"
			});
		}
		return undefined;

	} catch(error) {
		await NativeFileDocumentsUtils.writeToLog({
			actionName: "cropImageCleanupTempFiles",
			logType: "Exception",
			logMessage: JSON.stringify(error)
		});
		return Promise.reject(error);
	};
	// END USER CODE
}
