// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE

import RNBlobUtil from "react-native-blob-util";
import DownloadFileImpl from "../DownloadFileImpl";

// END EXTRA CODE

/**
 * @param {MxObject} request
 * @param {string} toFile
 * @param {Big} readTimeout
 * @param {boolean} writeToLog
 * @param {Big} [progressInterval] - Interval between progress updates in ms, defaults to 500ms
 * @param {Nanoflow} [onComplete] - Optional, will receive parameter named 'Result' with DownloadFileProgress object
 * @param {Nanoflow} [onError] - Optional, will receive parameter named 'Result' with DownloadFileProgress object
 * @returns {Promise.<MxObject>}
 */
export async function downloadFile(request, toFile, readTimeout, writeToLog, progressInterval, onComplete, onError) {
	// BEGIN USER CODE

	return DownloadFileImpl.downloadFile(RNBlobUtil, request, toFile, readTimeout, writeToLog, progressInterval, onComplete, onError);

	// END USER CODE
}
