// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import "mx-global";
import DeviceInfo from 'react-native-device-info';

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Gets the unique device ID
 * @returns {Promise.<string>}
 */
export async function getUniqueDeviceID() {
	// BEGIN USER CODE
	return DeviceInfo.getUniqueId();
	// END USER CODE
}
