// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE

import NativeFileDocumentsUtils from "../nativefiledocumentsutils";
import RNBlobUtil from "react-native-blob-util";
import { Platform } from 'react-native';

// END EXTRA CODE

/**
 * Moves the file located at filepath to destPath. Also allows renaming a file.
 * @param {string} filepath - The file to copy
 * @param {"NativeFileDocuments.PathType.FullPath"|"NativeFileDocuments.PathType.DocumentsDirectory"} filepathType
 * @param {string} destPath - The destination to copy to
 * @param {"NativeFileDocuments.PathType.FullPath"|"NativeFileDocuments.PathType.DocumentsDirectory"} destPathType
 * @param {boolean} writeToLog
 * @returns {Promise.<void>}
 */
export async function moveFile(filepath, filepathType, destPath, destPathType, writeToLog) {
	// BEGIN USER CODE
	if (!filepath) {
		return Promise.reject(new Error("No file path specified"));
	}
	if (!filepathType) {
		return Promise.reject(new Error("No path type specified"));
	}

	if (!destPath) {
		return Promise.reject(new Error("No destination path specified"));
	}
	if (!destPathType) {
		return Promise.reject(new Error("No destination type specified"));
	}

	if (writeToLog) {
		await NativeFileDocumentsUtils.writeToLog({
			actionName: "moveFile",
			logType: "Parameters",
			logMessage: JSON.stringify({
				filepath: filepath,
				filepathType: filepathType,
				destPath: destPath,
				destPathType: destPathType
			})
		});
	}

	const fullFilePath = NativeFileDocumentsUtils.getFullPathNoPrefix(filepath, filepathType, RNBlobUtil, Platform.OS);
	const fullDestPath = NativeFileDocumentsUtils.getFullPathNoPrefix(destPath, destPathType, RNBlobUtil, Platform.OS);

	if (writeToLog) {
		await NativeFileDocumentsUtils.writeToLog({
			actionName: "moveFile",
			logType: "Info",
			logMessage: "Full file path: " + fullFilePath + ", full dest path: " + fullDestPath
		});
	}

	return RNBlobUtil.fs.mv(fullFilePath, fullDestPath);

	// END USER CODE
}
