// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE

import NativeFileDocumentsUtils from "../nativefiledocumentsutils";
import RNBlobUtil from "react-native-blob-util";
import { Platform } from 'react-native';

// END EXTRA CODE

/**
 * Read contents from file as base64 encoded string.
 * Note that this can be slow and cause high memory usage with large files!
 * @param {string} filepath - The path to the file or directory.
 * @param {"NativeFileDocuments.PathType.FullPath"|"NativeFileDocuments.PathType.DocumentsDirectory"} pathType
 * @param {boolean} writeToLog
 * @returns {Promise.<string>}
 */
export async function readFile(filepath, pathType, writeToLog) {
	// BEGIN USER CODE

	if (!filepath) {
		return Promise.reject(new Error("No file path specified"));
	}
	if (!pathType) {
		return Promise.reject(new Error("No path type specified"));
	}
	if (writeToLog) {
		await NativeFileDocumentsUtils.writeToLog({
			actionName: "readFile",
			logType: "Parameters",
			logMessage: JSON.stringify({
				filepath: filepath,
				pathType: pathType
			})
		});
	}

	const fullPath = NativeFileDocumentsUtils.getFullPathNoPrefix(filepath, pathType, RNBlobUtil, Platform.OS);

	if (writeToLog) {
		await NativeFileDocumentsUtils.writeToLog({
			actionName: "readFile",
			logType: "Info",
			logMessage: "Full path: " + fullPath
		});
	}

	return RNBlobUtil.fs.readFile(fullPath, "base64");

	// END USER CODE
}
