// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE

import NativeFileDocumentsUtils from "../nativefiledocumentsutils";
import RNFS from "react-native-fs";
import { Platform } from 'react-native';

// END EXTRA CODE

/**
 * Reads the contents of dirpath.
 * @param {string} dirpath - Reads the contents of path.
 * @param {"NativeFileDocuments.PathType.FullPath"|"NativeFileDocuments.PathType.DocumentsDirectory"} pathType
 * @param {boolean} writeToLog
 * @returns {Promise.<MxObject[]>}
 */
export async function readDir(dirpath, pathType, writeToLog) {
	// BEGIN USER CODE
	if (!dirpath && pathType !== "DocumentsDirectory") {
		Promise.reject(new Error("No file path specified"));
	}
	if (!pathType) {
		Promise.reject(new Error("No path type specified"));
	}
	if (writeToLog) {
		NativeFileDocumentsUtils.writeToLog({
			actionName: "readDir",
			logType: "Parameters",
			logMessage: JSON.stringify({
				dirpath: dirpath,
				pathType: pathType
			})
		});
	}

	const fullPath = NativeFileDocumentsUtils.getFullPath(dirpath, pathType, RNFS, Platform.OS);

	if (writeToLog) {
		NativeFileDocumentsUtils.writeToLog({
			actionName: "readDir",
			logType: "Info",
			logMessage: "readDir fullPath: " + fullPath
		});
	}

	const dirItemArray = await RNFS.readDir(fullPath);

	const resultArray = [];

	for (item of dirItemArray) {
		const newResultItem = await NativeFileDocumentsUtils.createMxObject("NativeFileDocuments.ReadDirItem");
		newResultItem.set("Name", item.name);
		newResultItem.set("Path", item.path);
		newResultItem.set("Size", item.size);
		newResultItem.set("IsFile", item.isFile());
		newResultItem.set("IsDirectory", item.isDirectory());
		newResultItem.set("LastModified", item.mtime);
		resultArray.push(newResultItem);
	}

	return resultArray;

	// END USER CODE
}
