// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE

import LogListener from "../LogListener";

// END EXTRA CODE

/**
 * @param {string} logNode
 * @param {undefined|"trace"|"debug"|"info"|"warning"|"error"|"critical"|"none"} logLevel
 * @returns {Promise.<void>}
 */
export async function setLogLevel(logNode, logLevel) {
	// BEGIN USER CODE
	LogListener.setLogLevel(logNode, logLevel);
	// END USER CODE
}
