// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import RNFS from "react-native-fs";
// END EXTRA CODE

/**
 * @param {Big} jobId
 * @returns {Promise.<void>}
 */
export async function stopDownload(jobId) {
	// BEGIN USER CODE

	// no write to log, stopping a download will trigger an exception on the downloadFile
	RNFS.stopDownload(Number(jobId));
	// END USER CODE
}
