// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE

import DownloadFileImpl from "../DownloadFileImpl";

// END EXTRA CODE

/**
 * @param {MxObject} downloadFileProgress
 * @returns {Promise.<void>}
 */
export async function stopDownload(downloadFileProgress) {
	// BEGIN USER CODE

	DownloadFileImpl.stopDownload(downloadFileProgress);

	// END USER CODE
}
