// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE

import NativeFileDocumentsUtils from "../nativefiledocumentsutils";
import RNFS from "react-native-fs";
import { Platform } from "react-native";
import { unzip, unzipWithPassword } from "react-native-zip-archive";

// END EXTRA CODE

/**
 * Unzips the contents of the archive into the destination folder.
 * Note that this function expects an empty target folder.
 * 
 * Specify the password if the archive is password protected.
 * @param {string} filepath - The archive file
 * @param {"NativeFileDocuments.PathType.FullPath"|"NativeFileDocuments.PathType.DocumentsDirectory"} filepathType
 * @param {string} destPath - The destination to unzip to
 * @param {"NativeFileDocuments.PathType.FullPath"|"NativeFileDocuments.PathType.DocumentsDirectory"} destPathType
 * @param {boolean} writeToLog
 * @param {string} password - Archive password. Leave empty if archive has no password
 * @returns {Promise.<void>}
 */
export async function unzipToFolder(filepath, filepathType, destPath, destPathType, writeToLog, password) {
	// BEGIN USER CODE
	if (!filepath) {
		Promise.reject(new Error("No file path specified"));
	}
	if (!filepathType) {
		Promise.reject(new Error("No path type specified"));
	}

	if (!destPath) {
		Promise.reject(new Error("No destination path specified"));
	}
	if (!destPathType) {
		Promise.reject(new Error("No destination type specified"));
	}

	if (writeToLog) {
		NativeFileDocumentsUtils.writeToLog({
			actionName: "unzip",
			logType: "Parameters",
			logMessage: JSON.stringify({
				filepath: filepath,
				filepathType: filepathType,
				destPath: destPath,
				destPathType: destPathType
			})
		});
	}

	const fullFilePath = NativeFileDocumentsUtils.getFullPathNoPrefix(filepath, filepathType, RNFS, Platform.OS);
	const fullDestPath = NativeFileDocumentsUtils.getFullPathNoPrefix(destPath, destPathType, RNFS, Platform.OS);

	if (writeToLog) {
		NativeFileDocumentsUtils.writeToLog({
			actionName: "unzip",
			logType: "Info",
			logMessage: "Full file path: " + fullFilePath + ", full dest path: " + fullDestPath + ", has password: " + !!password
		});
	}

	if (password) {
		return unzipWithPassword(fullFilePath, fullDestPath, password);
	} else {
		return unzip(fullFilePath, fullDestPath);
	}

	// END USER CODE
}
