// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE

import NativeFileDocumentsUtils from "../nativefiledocumentsutils";
import RNFS from "react-native-fs";
import { Platform } from 'react-native';

// END EXTRA CODE

/**
 * Write text to a file.
 * As this is intended for use as logging, there is no writeToLog parameter.
 * @param {string} filepath - The path to the file or directory.
 * @param {"NativeFileDocuments.PathType.FullPath"|"NativeFileDocuments.PathType.DocumentsDirectory"} pathType
 * @param {string} textData
 * @param {boolean} append - Append to the existing file contents or write as only file contents.
 * @returns {Promise.<boolean>}
 */
export async function writeTextFile(filepath, pathType, textData, append) {
	// BEGIN USER CODE

	return new Promise(function (resolve, reject) {
		if (!filepath) {
			reject(new Error("No file path specified"));
		}
		if (!pathType) {
			reject(new Error("No path type specified"));
		}
		if (!textData) {
			reject(new Error("No data specified"));
		}

		const fullPath = NativeFileDocumentsUtils.getFullPath(filepath, pathType, RNFS, Platform.OS);

		if (append) {
			RNFS.appendFile(fullPath, textData, "utf8").then(() => {
				resolve(true);
			});
		} else {
			RNFS.writeFile(fullPath, textData, "utf8").then(() => {
				resolve(true);
			});
		}
	});

	// END USER CODE
}
