// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE

import NativeFileDocumentsUtils from "../nativefiledocumentsutils";
import RNBlobUtil from "react-native-blob-util";
import { Platform } from 'react-native';

// END EXTRA CODE

/**
 * Write text to a file.
 * As this is intended for use as logging, there is no writeToLog parameter.
 * @param {string} filepath - The path to the file or directory.
 * @param {undefined|"FullPath"|"DocumentsDirectory"} pathType
 * @param {string} textData
 * @param {boolean} append - Append to the existing file contents or write as only file contents.
 * @param {boolean} writeToLog
 * @returns {Promise.<void>}
 */
export async function writeTextFile(filepath, pathType, textData, append, writeToLog) {
	// BEGIN USER CODE

	if (!filepath) {
		return Promise.reject(new Error("No file path specified"));
	}
	if (!pathType) {
		return Promise.reject(new Error("No path type specified"));
	}
	if (!textData) {
		return Promise.reject(new Error("No data specified"));
	}
	if (writeToLog) {
		await NativeFileDocumentsUtils.writeToLog({
			actionName: "writeTextFile",
			logType: "Parameters",
			logMessage: JSON.stringify({
				filepath: filepath,
				pathType: pathType,
				append: append ? "yes" : "no",
				dataLength: textData.length
			})
		});
	}

	const fullPath = NativeFileDocumentsUtils.getFullPathNoPrefix(filepath, pathType, RNBlobUtil, Platform.OS);

	const fileExists = await RNBlobUtil.fs.exists(fullPath);

	if (writeToLog) {
		const logPrefix = fileExists ? "Existing" : "New";
		await NativeFileDocumentsUtils.writeToLog({
			actionName: "writeTextFile",
			logType: "Info",
			logMessage: logPrefix + " full path: " + fullPath
		});
	}

	if (fileExists) {
		if (append) {
			return RNBlobUtil.fs.appendFile(fullPath, textData, "utf8");
		} else {
			return RNBlobUtil.fs.writeFile(fullPath, textData, "utf8");
		}
	} else {
		return RNBlobUtil.fs.createFile(fullPath, textData, "utf8");
	}


	// END USER CODE
}
