// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * copies field values from mendix object src to mendix object tgt
 * @param {MxObject} src
 * @param {MxObject} tgt
 * @returns {Promise.<void>}
 */
export async function jsa_mxobj_copy_values(src, tgt) {
	// BEGIN USER CODE
	try{
		tgt.getAttributes().forEach((attr)=>{
			if(tgt.isReadonlyAttr(attr)){
				return;
			}
			else if(src.isBoolean(attr)){
				tgt.set(attr,src.get(attr));
			}
			else if(src.isDate(attr)){
				tgt.set(attr,src.get(attr));
			}
			else if(src.isEnum(attr)){
				tgt.set(attr,src.get(attr));
			}
			else if(src.isLocalizedDate(attr)){
				tgt.set(attr,src.get(attr));
			}
			else if(src.isNumeric(attr)){
				tgt.set(attr,src.get(attr));
			}
			else if(src.isPassword(attr)){
				tgt.set(attr,src.get(attr));
			}
			else{//string
				tgt.set(attr,src.get(attr));
			}
		});
		return Promise.resolve();
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
