// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import support from "../support/entidad";
// END EXTRA CODE

/**
 * Shuts down all agents and removes from cache
 * @returns {Promise.<void>}
 */
export async function jsa_aries_agents_shutdown() {
	// BEGIN USER CODE
	try{
		support.cache.keys().forEach(async(k)=>{
			try{
				let agent=support.cache.get(k);
				if(agent!=null){
					await agent.shutdown();
				};
			}catch(e){
				console.error(e.toString());
			}
			support.cache.remove(k);
		})
		return Promise.resolve();
	}catch(e){
		return Promise.reject(e.toString());
	}
	throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
