// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import{ConnectionEventTypes,ConnectionStateChangedEvent,DidExchangeState}from'@aries-framework/core';
import support from "../support/entidad";
// END EXTRA CODE

/**
 * @param {Big} agent_key
 * @param {"Aries.enum_aries_ConnectionEventTypes.ConnectionStateChanged"} connectionEventType
 * @param {Nanoflow} callback
 * @param {string} payloadParameterName
 * @param {string} userDataParameterName
 * @param {MxObject} userData
 * @returns {Promise.<void>}
 */
export async function jsa_aries_agent_events_setupConnectionListener(agent_key, connectionEventType, callback, payloadParameterName, userDataParameterName, userData) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");										//mandatory
		if(callback==null)return Promise.reject("Invalid callback parameter");											//mandatory
		if(connectionEventType==null)return Promise.reject("Invalid connectionEventType parameter");					//mandatory	
		switch(connectionEventType){
			case"ConnectionStateChanged":
				connectionEventType=ConnectionEventTypes.ConnectionStateChanged;
				break;
			default:
				return Promise.reject("Invalid connectionEventType parameter")
		}
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		agent.events.on(connectionEventType,({payload})=>{
			let args={};
			args[payloadParameterName]=JSON.stringify(payload);
			if(userDataParameterName!=null)args[userDataParameterName]=userData;
			callback(args);
		});
		return Promise.resolve();
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
