// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} json
 * @param {string} key
 * @returns {Promise.<string>}
 */
export async function jsa_json_get_key(json, key) {
	// BEGIN USER CODE
	try{
		let root=JSON.parse(json);
		let cur=root;
		key.split(".").forEach((k)=>{
			cur=cur[k]
		})
		let ret=null;
		switch(typeof(cur)){
			case"undefined":ret=null;break;
			case"string":ret=cur;break;
			default:ret=JSON.stringify(cur);break;
		}
		return Promise.resolve(ret);
	}catch(e){
		return Promise.reject(e.toString());
	}

	// END USER CODE
}
