// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import argon2 from 'react-native-argon2';
import{mx_data_createAsync}from"../support/entidad";
// END EXTRA CODE

/**
 * @param {string} password - e.g. 'password'
 * @param {string} salt - e.g. '1234567891011121314151617181920212223242526272829303132333435363'
 * @param {string} options - optional json
 * @returns {Promise.<MxObject>}
 */
export async function jsa_argon2(password, salt, options) {
	// BEGIN USER CODE
	if(options!=null){
		try{
			options=JSON.parse(options);
		}catch(e){
			return Promise.reject("invalid options argument: "+e.toString());
		}
	}else{
		options={};
	}
	const result=await argon2(password,salt,options);
	const{rawHash,encodedHash}=result;
	let o=await mx_data_createAsync({entity:"KeyManagement.Argon2Result"});
	o.set("rawHash",rawHash);
	o.set("encodedHash",encodedHash);
	return Promise.resolve(o);
	// END USER CODE
}
