// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * https://apidocs.rnd.mendix.com/9/client/mendix_lib_MxObject.html
 * 
 * getOriginalValue(attr) → {string|number|external:Big|boolean}
 * 
 * Returns the original, last committed, value of an attribute.
 * Parameters:
 * Name  Type  Description
 * attr  string  
 * 
 * attribute whose value to return
 * 
 * See:
 * 
 *         mendix/lib/MxObject#get for an overview of how the return value depends on the attribute's type.
 * 
 * Returns:
 * 
 * original value of the specified attribute.
 * 
 * Type 
 * @param {MxObject} input
 * @param {string} attribute
 * @returns {Promise.<string>}
 */
export async function jsa_mxobj_getOriginalValue(input, attribute) {
	// BEGIN USER CODE
	try{
		if(input==null)return Promise.reject("Invalid argument input");
		//todo:handle return type serialization
		return Promise.resolve(input.getOriginalValue(attribute));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
