// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Generates uuid
 * @returns {Promise.<string>}
 */
export async function jsa_uuid() {
	// BEGIN USER CODE
	try{
                //https://stackoverflow.com/questions/105034/how-do-i-create-a-guid-uuid
                let d=new Date().getTime();
                let d2=((typeof performance!=="undefined")&&performance.now&&(performance.now()*1000))||0;
                return Promise.resolve("xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(c){
                        let r=Math.random()*16;
                        if(d>0){
                                r=(d+r)%16|0;
                                d=Math.floor(d/16);
                        }else{
                                r=(d2+r)%16|0;
                                d2=Math.floor(d2/16);
                        }
                        return(c==="x"?r:(r&0x3|0x8)).toString(16);
                }));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
