// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
import{default as jsonQuery}from"json-query";
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function jsa_test_tmp() {
	// BEGIN USER CODE
	try{
		console.info("jsa_test_tmp:beg");
		console.info(typeof(jsonQuery));
		console.info(JSON.stringify(Object.keys(jsonQuery)));
		let data = {
			people: [
				{name: 'Matt', country: 'NZ'},
				{name: 'Pete', country: 'AU'},
				{name: 'Mikey', country: 'NZ'}
			]
		};
		console.info(JSON.stringify(data));
		let result=jsonQuery('people[country=NZ].name', {
			data: data
		}); //=> {value: 'Matt', parents: [...], key: 0} ... etc
		console.info(JSON.stringify(result));
		console.info("jsa_test_tmp:end");
		return Promise.resolve();
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
