// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import { NativeModules, Platform } from "react-native";
// END EXTRA CODE

/**
 *  One-shot read of a value written by the OLD react-native-sensitive-info@6.0.0-alpha.9
 *  (non-biometric Android path). Backed by the LegacySensitiveInfoReader native module.
 *  Android-only: resolves null on iOS/web (iOS 6.1.4 already reads old keychain data directly).
 *  Resolves null when there is nothing to migrate (entry absent, or old Keystore key gone).
 * @param {string} key - the exact key the old app stored the value under (e.g. the seed key)
 * @param {string} [sharedPreferencesName] - optional; the old SharedPreferences file name. Defaults to "shared_preferences".
 * @returns {Promise.<string>}
 */
export async function jsa_legacy_android_read(key, sharedPreferencesName) {
	// BEGIN USER CODE
	try{
		if(Platform.OS!=="android")return Promise.resolve(null);
		const mod=NativeModules.LegacySensitiveInfoReader;
		if(mod==null)return Promise.reject("LegacySensitiveInfoReader native module not linked - add LegacyMigrationPackage to the native template and rebuild");
		const plain=await mod.readLegacy(sharedPreferencesName!=null&&sharedPreferencesName!=""?sharedPreferencesName:null,key);
		return Promise.resolve(plain!=null?plain:null);
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
