// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";
import * as SInfo from "react-native-sensitive-info";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Check whether a secret exists (no biometric prompt).
 * @param {string} key - Secret identifier
 * @param {string} [service] - Logical namespace for secrets. Defaults to "KeyManagement" when null.
 * @param {string} [keychainGroup] - Apple only — keychain access group.
 * @returns {Promise.<boolean>}
 */
export async function jsa_hasItem(key, service, keychainGroup) {
	// BEGIN USER CODE
	try{
		//cheap existence check: never decrypts, never prompts (even for biometric-gated entries)
		const svc=(service!=null&&service!="")?service:"KeyManagement";
		const options={service:svc};
		//Apple-only keychain access group; omitted unless provided.
		if(keychainGroup!=null&&keychainGroup!="")options.keychainGroup=keychainGroup;
		const exists=await SInfo.hasItem(key,options);
		return Promise.resolve(exists===true);
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
