// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import argon2 from "react-native-argon2";

// Vectors are embedded so this action is self-contained and can be dropped into
// both the current (2.0.1) and upgraded (4.0.0) Mendix apps without extra files.
// Keep this list identical between the golden capture and the candidate run.
const VECTORS = {
	mustMatch: [
		{ id: "default-empty-options", password: "password", salt: "1234567891011121314151617181920212223242526272829303132333435363", options: {} },
		{ id: "explicit-defaults-argon2id", password: "password", salt: "1234567891011121314151617181920212223242526272829303132333435363", options: { iterations: 2, memory: 32768, parallelism: 1, hashLength: 32, mode: "argon2id" } },
		{ id: "mnemonic-like-seed", password: "legal winner thank year wave sausage worth useful legal winner thank yellow", salt: "mendix-keymanagement-fixed-salt-00000000000000000000000000000000", options: {} },
		{ id: "unicode-password", password: "correct horse battery staple - cafe coffee unicode test", salt: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef", options: { mode: "argon2id" } },
		{ id: "argon2i-variant", password: "password", salt: "1234567891011121314151617181920212223242526272829303132333435363", options: { mode: "argon2i" } },
		{ id: "argon2d-variant", password: "password", salt: "1234567891011121314151617181920212223242526272829303132333435363", options: { mode: "argon2d" } },
		{ id: "high-cost-params", password: "password", salt: "1234567891011121314151617181920212223242526272829303132333435363", options: { iterations: 4, memory: 65536, parallelism: 2, hashLength: 64, mode: "argon2id" } }
	],
	controls_expectedToDiverge: [
		{ id: "CONTROL-hex-salt-footgun", password: "password", salt: "1234567891011121314151617181920212223242526272829303132333435363", options: { saltEncoding: "hex" } }
	]
};
// END EXTRA CODE

/**
 * @returns {Promise.<string>}
 */
export async function jsa_argon2_equivalence_probe() {
	// BEGIN USER CODE
	const all = [...VECTORS.mustMatch, ...VECTORS.controls_expectedToDiverge];
	const results = [];
	for (const v of all) {
		try {
			const { rawHash, encodedHash } = await argon2(v.password, v.salt, v.options || {});
			results.push({ id: v.id, ok: true, rawHash, encodedHash });
		} catch (e) {
			results.push({ id: v.id, ok: false, error: String(e && e.message ? e.message : e) });
		}
	}
	// Returned as a string so it can be shown in a text area / logged and copied off-device.
	return Promise.resolve(JSON.stringify(results, null, 2));
	// END USER CODE
}
