// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";
import * as SInfo from "react-native-sensitive-info";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Remove a secret. Returns true if something was deleted.
 * @param {string} key - Secret identifier
 * @param {string} [service] - Logical namespace for secrets. Defaults to "KeyManagement" when null.
 * @param {boolean} [iosSynchronizable] - Apple-only iCloud Keychain sync, default off
 * @param {string} [keychainGroup] - Apple only — keychain access group. 
 * @returns {Promise.<boolean>}
 */
export async function jsa_deleteItem(key, service, iosSynchronizable, keychainGroup) {
	// BEGIN USER CODE
	try{
		const svc=(service!=null&&service!="")?service:"KeyManagement";
		const options={service:svc};
		//Apple-only scope options; omitted unless provided.
		if(iosSynchronizable===true)options.iosSynchronizable=true;
		if(keychainGroup!=null&&keychainGroup!="")options.keychainGroup=keychainGroup;
		const removed=await SInfo.deleteItem(key,options);
		return Promise.resolve(removed===true);
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
