// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";
import * as SInfo from "react-native-sensitive-info";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * List all secrets in a service.
 * @param {string} [service] - Logical namespace for secrets. Defaults to "KeyManagement" when null.
 * @param {boolean} [includeValues] - default true. false = metadata-only read: cheaper, and on iOS skips the biometric prompt for a gated entry.
 * @param {boolean} [iosSynchronizable] - Apple-only iCloud Keychain sync, default off
 * @param {string} [keychainGroup] - Apple only — keychain access group.
 * @returns {Promise.<string>}
 */
export async function jsa_getAllItems(service, includeValues, iosSynchronizable, keychainGroup) {
	// BEGIN USER CODE
	try{
		const svc=(service!=null&&service!="")?service:"KeyManagement";
		//6.1.x returns SensitiveInfoItem[] ({key,service,value,metadata}).
		//includeValues defaults true (return values); false = metadata-only (keys only, cheaper, no prompt).
		const options={service:svc,includeValues:(includeValues===false)?false:true};
		//Apple-only scope options; omitted unless provided.
		if(iosSynchronizable===true)options.iosSynchronizable=true;
		if(keychainGroup!=null&&keychainGroup!="")options.keychainGroup=keychainGroup;
		const items=await SInfo.getAllItems(options);
		//flat array: one {service,key,value} object per entry
		const result=(Array.isArray(items)?items:[])
			.filter((it)=>it&&typeof(it.key)=="string")
			.map((it)=>({
				service:typeof(it.service)=="string"?it.service:"",
				key:it.key,
				value:(it.value!==undefined?it.value:null)
			}));
		return Promise.resolve(JSON.stringify(result));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
