// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";
import * as SInfo from "react-native-sensitive-info";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Snapshot of device capabilities (secureEnclave, strongBox, biometry, biometryStatus, deviceCredential) as JSON
 * @returns {Promise.<string>}
 */
export async function jsa_getSupportedSecurityLevels() {
	// BEGIN USER CODE
	try{
		const caps=await SInfo.getSupportedSecurityLevels();
		return Promise.resolve(JSON.stringify(caps!=null?caps:{}));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
