// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";
import * as SInfo from "react-native-sensitive-info";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 *  Cross-platform biometric-sensor availability (react-native-sensitive-info 6.1.x).
 *  * Replaces jsa_ios_isSensorAvailable / jsa_android_isSensorAvailable.
 *  * Backed by getSupportedSecurityLevels().biometry (true when biometry is present AND enrolled AND usable).
 * @returns {Promise.<boolean>}
 */
export async function jsa_isSensorAvailable() {
	// BEGIN USER CODE
	try{
		const caps=await SInfo.getSupportedSecurityLevels();
		return Promise.resolve(caps!=null&&caps.biometry===true);
	}catch(e){
		//preserve the old actions' behavior of resolving false rather than rejecting on probe failure
		console.error("jsa_isSensorAvailable:error: "+e.toString());
		return Promise.resolve(false);
	}
	// END USER CODE
}
