// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";
import * as SInfo from "react-native-sensitive-info";

// BEGIN EXTRA CODE
// jsa_hasEnrolledFingerprints — cross-platform "has enrolled biometrics" check (react-native-sensitive-info 6.1.x).
// Replaces jsa_android_hasEnrolledFingerprints (now cross-platform). Takes no parameters.
// Backed by getSupportedSecurityLevels().biometryStatus === "available"
// (distinguishes "enrolled & usable" from "hardware present but not enrolled").
// Returns boolean; resolves false rather than rejecting on probe failure.
// END EXTRA CODE

/**
 * cross-platform "has enrolled biometrics" check (react-native-sensitive-info 6.1.x).
 * * Replaces jsa_android_hasEnrolledFingerprints (now cross-platform). Takes no parameters.
 * * Backed by getSupportedSecurityLevels().biometryStatus === "available"
 * * (distinguishes "enrolled & usable" from "hardware present but not enrolled").
 * * Returns boolean; resolves false rather than rejecting on probe failure.
 * @returns {Promise.<boolean>}
 */
export async function jsa_hasEnrolledFingerprints() {
	// BEGIN USER CODE
	try{
		const caps=await SInfo.getSupportedSecurityLevels();
		return Promise.resolve(caps!=null&&caps.biometryStatus==="available");
	}catch(e){
		console.error("jsa_hasEnrolledFingerprints:error: "+e.toString());
		return Promise.resolve(false);
	}
	// END USER CODE
}
