// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";
import * as SInfo from "react-native-sensitive-info";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Write a secret using the strongest available security policy.
 * @param {string} key - Secret identifier
 * @param {string} value - Secret
 * @param {string} [service] - Logical namespace for secrets. Defaults to "KeyManagement" when null.
 * @param {string} accessControl - Preferred write policy; native layer picks the strongest supported fallback. Allowed options: "secureEnclaveBiometry", "biometryCurrentSet", "biometryAny", "devicePasscode","none"
 * @param {boolean} [iosSynchronizable] - Apple-only iCloud Keychain sync, default off
 * @param {string} [promptTitle] - gates the prompt — no title, no authenticationPrompt
 * @param {string} [promptSubtitle] - Android only
 * @param {string} [promptDescription] - Android only
 * @param {string} [promptCancel] - both platforms
 * @param {string} [keychainGroup] - Apple only — keychain access group.
 * @returns {Promise.<boolean>}
 */
export async function jsa_setItem(key, value, service, accessControl, iosSynchronizable, promptTitle, promptSubtitle, promptDescription, promptCancel, keychainGroup) {
	// BEGIN USER CODE
	try{
		const svc=(service!=null&&service!="")?service:"KeyManagement";
		//accessControl is a WRITE policy; default "none" (encrypted at rest, no biometric prompt).
		//Validate explicitly so a misconfigured value fails loud rather than silently mis-protecting a key.
		const ALLOWED=["secureEnclaveBiometry","biometryCurrentSet","biometryAny","devicePasscode","none"];
		let ac="none";
		if(accessControl!=null&&accessControl!=""){
			if(ALLOWED.indexOf(accessControl)<0)return Promise.reject("Invalid accessControl \""+accessControl+"\". Allowed: "+ALLOWED.join(", "));
			ac=accessControl;
		}
		const options={service:svc,accessControl:ac};
		//Apple-only scope options; omitted unless provided so the lib keeps its defaults.
		if(iosSynchronizable===true)options.iosSynchronizable=true;
		if(keychainGroup!=null&&keychainGroup!="")options.keychainGroup=keychainGroup;
		//authenticationPrompt: strings shown when user presence is required. The API requires a
		//title, so only build the prompt when one is supplied. subtitle/description are Android-only.
		if(promptTitle!=null&&promptTitle!=""){
			const prompt={title:promptTitle};
			if(promptSubtitle!=null&&promptSubtitle!="")prompt.subtitle=promptSubtitle;
			if(promptDescription!=null&&promptDescription!="")prompt.description=promptDescription;
			if(promptCancel!=null&&promptCancel!="")prompt.cancel=promptCancel;
			options.authenticationPrompt=prompt;
		}
		await SInfo.setItem(key,value,options);
		return Promise.resolve(true);
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
