// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
import {jsa_mxobj2json} from"./jsa_mxobj2json.js";
import {jsa_json2mxobj} from"./jsa_json2mxobj.js";
import {jsa_uuid} from"./jsa_uuid.js";
import SInfo from "react-native-sensitive-info";
// END EXTRA CODE

/**
 * Gets a single Mendix object from the keychain
 * @param {string} key
 * @param {MxObject} output - object to populate
 * @param {string} idattr - optional, name of attribute containing id
 * @param {string} idval - optional, manual id value
 * @returns {Promise.<boolean>}
 */
export async function jsa_kcorm_get_one(key, output, idattr, idval) {
	// BEGIN USER CODE
	try{
		if(output==null)return Promise.reject("Argument output null");
		if(key==null)return Promise.reject("Argument key null");
		let obj={};
		try{
			//https://mcodex.dev/react-native-sensitive-info/docs/getItem
			let kcval=await SInfo.getItem(key,{});
			if(kcval!=null&&kcval!="")try{
				obj=JSON.parse(kcval);
				obj=typeof(obj)=="object"?obj:Array.isArray(obj)?{}:obj;
			}catch(e){
				console.error(e.toString());
				//todo:handle/log
			}
		}catch(e){
			//todo:handle/log
			console.error(e.toString());
		}
		let module_=output.getEntity().split(".")[0];
		if(module_==null||module_=="")return Promise.reject("Invalid entity module name")
		let entity_=output.getEntity().split(".")[1];
		if(entity_==null||entity_=="")return Promise.reject("Invalid entity name")
		//throw on module or entity subobjects not found 
		if(typeof(obj[module_])!="object")return Promise.reject("Module "+module_+" not found");
		if(typeof(obj[module_][entity_])!="object")return Promise.reject("Entity "+entity_+" not found");
		let uuid=null;
		// 1. by id_ field as specified in the java action parameter
		if(idattr!=null&&output.has(idattr)&&output.get(idattr)!=null){
			uuid=output.get(idattr);
		// 2. by field with name "id_"
		}else if(output.has("id_")&&output.get("id_")!=null){
			uuid=output.get("id_");
		}
		// 3. by manual id value or uuid from a utility function 
		if(uuid==null||typeof(uuid)!="string"||uuid.length==0){
			if(idval!=null&&typeof(idval)=="string"&&idval.length==0){
				uuid=idval;
			}else{
				return Promise.reject("Cannot determine id");
			}
		}
		console.info("Getting "+[module_,entity_,uuid].join("."));
		if(typeof(obj[module_][entity_][uuid])=="undefined")return Promise.reject([module_,entity_,uuid].join(".")+" not found")
		await jsa_json2mxobj(JSON.stringify(obj[module_][entity_][uuid]),output);
		//todo: return values
		return Promise.resolve(true);
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
