// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";
import * as SInfo from "react-native-sensitive-info";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Read a secret and its metadata. Pass includeValue: false to skip the payload.
 * @param {string} key - Secret identifier
 * @param {string} [service] - Logical namespace for secrets. Defaults to "KeyManagement" when null.
 * @param {boolean} [includeValue] - default true. false = metadata-only read: cheaper, and on iOS skips the biometric prompt for a gated entry.
 * @param {boolean} [iosSynchronizable] - Apple-only iCloud Keychain sync, default off
 * @param {string} [promptTitle] - gates the prompt — no title, no authenticationPrompt
 * @param {string} [promptSubtitle] - Android only
 * @param {string} [promptDescription] - Android only
 * @param {string} [promptCancel] - Both platforms
 * @param {string} [keychainGroup] - Apple only — keychain access group.
 * @returns {Promise.<string>}
 */
export async function jsa_getItem(key, service, includeValue, iosSynchronizable, promptTitle, promptSubtitle, promptDescription, promptCancel, keychainGroup) {
	// BEGIN USER CODE
	try{
		const svc=(service!=null&&service!="")?service:"KeyManagement";
		//includeValue defaults true (return the decrypted value); false = metadata-only (and on iOS skips the prompt)
		const options={service:svc,includeValue:(includeValue===false)?false:true};
		//Apple-only scope options; omitted unless provided so the lib keeps its defaults
		if(iosSynchronizable===true)options.iosSynchronizable=true;
		if(keychainGroup!=null&&keychainGroup!="")options.keychainGroup=keychainGroup;
		//authenticationPrompt: strings for a value read requiring user presence; the lib applies it only
		//when includeValue is true. title is required, so build the prompt only when a title is supplied.
		if(promptTitle!=null&&promptTitle!=""){
			const prompt={title:promptTitle};
			if(promptSubtitle!=null&&promptSubtitle!="")prompt.subtitle=promptSubtitle;
			if(promptDescription!=null&&promptDescription!="")prompt.description=promptDescription;
			if(promptCancel!=null&&promptCancel!="")prompt.cancel=promptCancel;
			options.authenticationPrompt=prompt;
		}
		//6.1.x getItem returns {key,service,value,metadata} | null (was a raw string in the old bridge API)
		const item=await SInfo.getItem(key,options);
		if(item==null)return Promise.resolve(null);
		return Promise.resolve(item.value!=null?item.value:null);
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
