// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {Nanoflow} nano
 * @param {Big} parameter1
 * @param {Big} parameter2
 * @returns {Promise.<Big>}
 */
export async function JS_CallNano(nano, parameter1, parameter2) {
	// BEGIN USER CODE
	return nano({a: parameter1, b:parameter2});
	//throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
