// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import support from "../../agent_sdk/support/entidad";
// END EXTRA CODE

/**
 *   public createResponseListener(
 *     callback: (params: { drpcMessageRecord: DrpcRecord; removeListener: () => void }) => void | Promise<void>
 *   )
 * @param {string} agent_key
 * @param {string} params_drpcMessageRecord
 * @returns {Promise.<void>}
 */
export async function jsa_aries_agent_modules_drpc_drpcMessageService_createResponseListener(agent_key, params_drpcMessageRecord) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return(Promise.reject("Invalid agent_key parameter"));
		if(params_drpcMessageRecord==null)params_drpcMessageRecord="drpcMessageRecord";
		let agent=support.cache.get(agent_key);
		if(agent==null)return(Promise.reject("Agent not found in cache"));
		await agent.modules.drpc.drpcMessageService.createResponseListener((params)=>{
			let args={};
			args[params_drpcMessageRecord]=params.drpcMessageRecord;
			callback(args);
		});
		return(Promise.resolve());
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
