// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * throws exception
 * @param {string} message
 * @returns {Promise.<void>}
 */
export async function jsa_throw_exception(message) {
	// BEGIN USER CODE
	try{
		return new Promise(function(resolve,reject){
			reject(message);
		});
	}catch(e){
		throw new Error(e.toString());
	}
	// END USER CODE
}
