// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import{cache}from"../support/entidad";
// END EXTRA CODE

/**
 * Returns JSON array of registered callbacks
 * @returns {Promise.<string>}
 */
export async function jsa_aries_agent_modules_rpc_get_registiered_callbacks() {
	// BEGIN USER CODE
	try{
		if(alias==null||alias=="")return(Promise.reject("Invalid alias parameter"));
		return(Promise.resolve(JSON.stringify(cache.list())));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
