// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import{cache}from"../support/entidad";
// END EXTRA CODE

/**
 * Registers RPC callback
 * @param {string} alias
 * @param {Nanoflow} callback
 * @param {string} hint - optional
 * @param {string} parameter - optional
 * @returns {Promise.<void>}
 */
export async function jsa_aries_agent_modules_rpc_register_callback(alias, callback, hint, parameter) {
	// BEGIN USER CODE
	try{
		if(alias==null)return Promise.reject("Invalid alias parameter");
		if(callback==null)return Promise.reject("Invalid callback parameter");
		if(hint!=null){
			try{
				hint=JSON.parse(hint);
			}catch(e){
				return(Promise.reject("Invalid hint: "+e.toString()));
			}
		}
		cache.put({callback:callback,hint:hint,parameter:parameter},alias)
		window.cache=cache;
		return(Promise.resolve());
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
