// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import { DrpcStateChanged, DrpcEventTypes  } from '../../agent_sdk/node_modules/@credo-ts/drpc'
import support from "../../agent_sdk/support/entidad";
import{cache}from"../support/entidad";
// END EXTRA CODE

/**
 * Unregisters RPC method
 * @param {string} alias - optional
 * @param {Nanoflow} callback - optional
 * @returns {Promise.<void>}
 */
export async function jsa_aries_agent_modules_rpc_unregister_callback(alias, callback) {
	// BEGIN USER CODE
	try{
		//todo
		//todo
		return(Promise.resolve());
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
