// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {MxObject} obj
 * @returns {Promise.<void>}
 */
export async function jsa_mxobj_clearfields(obj) {
	// BEGIN USER CODE
	try{
		obj.getAttributes().forEach((attr)=>{
			if(obj.isReadonlyAttr(attr)){
				return;
			}
			else if(obj.isBoolean(attr)){
				//obj.set(attr,false/*?*/);
			}
			else if(obj.isDate(attr)){
				obj.set(attr,null);
			}
			else if(obj.isEnum(attr)){
				obj.set(attr,null);
			}
			else if(obj.isLocalizedDate(attr)){
				obj.set(attr,null);
			}
			else if(obj.isNumeric(attr)){
				obj.set(attr,null);
			}
			else if(obj.isObjectReference(attr)){
				//obj.set(attr);
			}
			else if(obj.isObjectReferenceSet(attr)){
				//obj.set(attr);
			}
			else if(obj.isPassword(attr)){
				obj.set(attr,null);
			}
			else if(obj.isReference(attr)){
				//obj.set(attr);
			}
			else{//string
				obj.set(attr,null);
			}
		});
		return Promise.resolve();
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
